# Generated by Django 4.1.7 on 2023-04-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
