# Generated by Django 4.1.7 on 2023-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
