# Generated by Django 4.1.7 on 2023-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('offer', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
