# Generated by Django 4.1.7 on 2023-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproducts',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fproducts',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
