# Generated by Django 4.1.7 on 2023-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_aproducts_name_alter_fproducts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fproducts',
            name='name',
            field=models.TextField(max_length=1000),
        ),
    ]
