# Generated by Django 4.1.7 on 2023-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproducts',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fproducts',
            name='name',
            field=models.TextField(max_length=2000),
        ),
    ]
