# Generated by Django 4.1.7 on 2023-04-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aproducts_name_alter_fproducts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fproducts',
            name='category',
        ),
        migrations.DeleteModel(
            name='AProducts',
        ),
        migrations.DeleteModel(
            name='FProducts',
        ),
    ]
