# Generated by Django 4.1.7 on 2023-04-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fproducts_category_delete_aproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000)),
                ('fid', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('offer', models.CharField(max_length=100)),
                ('price', models.JSONField(default=list)),
                ('date', models.JSONField(default=list)),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='AProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('aid', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('offer', models.CharField(max_length=100)),
                ('price', models.JSONField(default=list)),
                ('date', models.JSONField(default=list)),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
